Feature/7
andmatcha/BB pull request #9
Opened 2022-08-26 03:01 UTC by KEISHIRO-TERASHITA

### やったこと
ログインページの見た目だけ作った

2022-08-26 09:43 UTC, andmatcha requested changes
コメントしました〜

2022-08-26 09:43 UTC, andmatcha commented on src/html/login/index.php
> +cInputSection("パスワード", "password", "text", []);
```suggestion
cInputSection('メールアドレス', 'email', 'email');
cInputSection('パスワード', 'password', 'password');
```

- 空配列なら第四引数書かなくてOK
- メールアドレスはtype属性とname属性をemailってするのがいいかも
- パスワードもtype属性はpasswordで
- PHPの文字列は基本シングルクオートで統一したい、他のところも'にしてもらえるとgood

まあ見た目だけだから別にいいかとも思うけど、一応修正お願いー
疑問点あれば聞いてー

2022-08-27 06:33 UTC, andmatcha requested changes
再度コメントしました〜

2022-08-27 06:33 UTC, andmatcha commented on src/html/login/getLoginData.php
> +  header('location:index.php?empty_info=true');
```suggestion
  header('Location: index.php?empty_info=true');
```
これが正しいと思う

2022-08-27 06:33 UTC, andmatcha commented on src/html/login/index.php
> +cInputSection('メールアドレス', 'email', 'e-mail');
```suggestion
cInputSection('メールアドレス', 'email', 'email');
```
これが正しいとおもう〜

2022-08-27 07:03 UTC, KEISHIRO-TERASHITA commented on src/html/login/index.php
> +cInputSection('メールアドレス', 'email', 'e-mail');
なんか反応しないと思ったら、書き方間違えてたか...

2022-08-27 07:04 UTC, KEISHIRO-TERASHITA commented on src/html/login/getLoginData.php
> +  header('location:index.php?empty_info=true');
このままでも動くけど、調べると確かに大文字とスペース入ってるね。見やすいし、直しときました！

2022-08-27 07:07 UTC, andmatcha approved these changes
LGTM〜

2022-08-27 07:13 UTC, merged